# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{noodall-ui}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve England"]
  s.date = %q{2010-09-27}
  s.description = %q{Noodall Rails User Interface Engine. Requires Noodall Core}
  s.email = %q{steve@wearebeef.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/noodall/admin/assets_controller.rb",
    "app/controllers/noodall/admin/components_controller.rb",
    "app/controllers/noodall/admin/groups_controller.rb",
    "app/controllers/noodall/admin/nodes_controller.rb",
    "app/controllers/noodall/nodes_controller.rb",
    "app/helpers/noodall/admin/assets_helper.rb",
    "app/helpers/noodall/admin/base_helper.rb",
    "app/helpers/noodall/admin/nodes_helper.rb",
    "app/helpers/noodall/components_helper.rb",
    "app/helpers/noodall/nodes_helper.rb",
    "app/helpers/noodall/permalinks.rb",
    "app/models/asset.rb",
    "app/views/noodall/admin/assets/_browser.html.erb",
    "app/views/noodall/admin/assets/_form.html.erb",
    "app/views/noodall/admin/assets/_menu.html.erb",
    "app/views/noodall/admin/assets/_show.html.erb",
    "app/views/noodall/admin/assets/_tags.html.erb",
    "app/views/noodall/admin/assets/add.html.erb",
    "app/views/noodall/admin/assets/form.html.erb",
    "app/views/noodall/admin/assets/form.js.erb",
    "app/views/noodall/admin/assets/index.html.erb",
    "app/views/noodall/admin/assets/index.js.erb",
    "app/views/noodall/admin/assets/show.html.erb",
    "app/views/noodall/admin/assets/show.js.erb",
    "app/views/noodall/admin/assets/tags.html.erb",
    "app/views/noodall/admin/assets/tags.js.erb",
    "app/views/noodall/admin/components/_articles_archive.html.erb",
    "app/views/noodall/admin/components/_comment_area.html.erb",
    "app/views/noodall/admin/components/_component.erb",
    "app/views/noodall/admin/components/_contact_form.html.erb",
    "app/views/noodall/admin/components/_download.html.erb",
    "app/views/noodall/admin/components/_gallery.html.erb",
    "app/views/noodall/admin/components/_general_content.html.erb",
    "app/views/noodall/admin/components/_hero_panel.html.erb",
    "app/views/noodall/admin/components/_latest_content.html.erb",
    "app/views/noodall/admin/components/_multi_file_images.html.erb",
    "app/views/noodall/admin/components/_open_day_list.html.erb",
    "app/views/noodall/admin/components/_promo.html.erb",
    "app/views/noodall/admin/components/_quote.html.erb",
    "app/views/noodall/admin/components/_upcoming_events_list.html.erb",
    "app/views/noodall/admin/nodes/_article_page.html.erb",
    "app/views/noodall/admin/nodes/_articles_list.html.erb",
    "app/views/noodall/admin/nodes/_body.html.erb",
    "app/views/noodall/admin/nodes/_branch.html.erb",
    "app/views/noodall/admin/nodes/_course_page.html.erb",
    "app/views/noodall/admin/nodes/_event_page.html.erb",
    "app/views/noodall/admin/nodes/_events_list.html.erb",
    "app/views/noodall/admin/nodes/_home.html.erb",
    "app/views/noodall/admin/nodes/_landing_page.html.erb",
    "app/views/noodall/admin/nodes/_page_a.html.erb",
    "app/views/noodall/admin/nodes/_page_b.html.erb",
    "app/views/noodall/admin/nodes/_school_landing_page.html.erb",
    "app/views/noodall/admin/nodes/_slot_form.html.erb",
    "app/views/noodall/admin/nodes/_study_landing_page.html.erb",
    "app/views/noodall/admin/nodes/change_template.html.erb",
    "app/views/noodall/admin/nodes/index.html.erb",
    "app/views/noodall/admin/nodes/new.html.erb",
    "app/views/noodall/admin/nodes/show.html.erb",
    "app/views/noodall/admin/nodes/tree.html.erb",
    "app/views/noodall/admin/nodes/tree.js.erb",
    "app/views/noodall/components/_component.erb",
    "app/views/noodall/layouts/admin.html.erb",
    "app/views/noodall/nodes/search.html.erb",
    "app/views/noodall/nodes/sitemap.html.erb",
    "app/views/noodall/nodes/sitemap.xml.rxml",
    "features/change_templates.feature",
    "features/content.feature",
    "features/content_modules.feature",
    "features/content_templates.feature",
    "features/manage_assets.feature",
    "features/manage_content_tree.feature",
    "features/preview.feature",
    "features/publish_content.feature",
    "features/search.feature",
    "features/sitemap.feature",
    "features/step_definitions/asset_steps.rb",
    "features/step_definitions/cms_node_steps.rb",
    "features/step_definitions/content_steps.rb",
    "features/step_definitions/groups_access_steps.rb",
    "features/step_definitions/module_steps.rb",
    "features/step_definitions/node_steps.rb",
    "features/step_definitions/preview_steps.rb",
    "features/step_definitions/pubish_content_steps.rb",
    "features/step_definitions/search_steps.rb",
    "features/support/paths.rb",
    "lib/noodall-ui.rb",
    "spec/factories/asset.rb",
    "spec/factories/component.rb",
    "spec/factories/node.rb",
    "spec/files/beef.png",
    "spec/files/get_video.flv",
    "spec/files/test.pdf",
    "spec/noodall-ui_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/beef/noodall-ui}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Noodall Rails User Interface}
  s.test_files = [
    "spec/factories/asset.rb",
    "spec/factories/component.rb",
    "spec/factories/node.rb",
    "spec/noodall-ui_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.0"])
      s.add_runtime_dependency(%q<noodall-core>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.0.0.beta.22"])
      s.add_development_dependency(%q<spork>, [">= 0"])
      s.add_development_dependency(%q<launchy>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.0"])
      s.add_dependency(%q<noodall-core>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.0.0.beta.22"])
      s.add_dependency(%q<spork>, [">= 0"])
      s.add_dependency(%q<launchy>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.0"])
    s.add_dependency(%q<noodall-core>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.0.0.beta.22"])
    s.add_dependency(%q<spork>, [">= 0"])
    s.add_dependency(%q<launchy>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre3"])
  end
end

